from src.stage_00_data_loader import DataLoader
from src.stage_01_data_validation import DataValidation
from src.stage_03_data_preprocessing import DataPreprocessing
from src.stage_04_model_training import ModelTraining
from src.stage_05_model_evaluation import ModelEvaluation
from src.stage_06_model_deployment import ModelDeployment
